[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.34"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
